name: ID Example

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
  
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          echo ${{ github}}
      
      - name: Run Python Script
        run: python test.py
      
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests Flask 
          pip list
          
      
      - name: Run Python Commands multi line
        uses: jannekem/run-python-script-action@v1
        id: script
        with:
          fail-on-error: false
          script: |
            from flask import Flask, request
            app = Flask(__name__)
            @app.route('/', methods=['POST'])
            def result():
                print(request.form['ref']) # should display 'bar'
                return 'Received !' # response to your request.
