on:
  workflow_dispatch:
    inputs:
      
      serverName:
        description: 'Please Provide the Server Name'
        type: string
        required: true 
      

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ github.event.inputs.serverName == 'true' }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ github.event.inputs.serverName }} 
