on:
  workflow_dispatch:
    inputs:
      
      ARM_SERVER_NAME:
        description: 'Please Provide the Server Name'
        type: string
        required: true 
      JAVA_INSTALLER:
        description: 'Please Provide the JAVA_INSTALLER'
        default: 'OpenJDK8U-jdk_x64_windows_hotspot_8u322b06.msi'
        required: true
      MULE_INSTALLER_FILE:
        description: 'Please Provide the MULE_INSTALLER_FILE'
        default: 'jda-connect-mule4-server-installation-2019.1.1-1.zip'
        required: true
      VS_CODE_INSTALLER:
        description: 'Please Provide the VS_CODE_INSTALLER'
        default: 'VSCodeUserSetup-x64-1.66.0.exe'
        required: true
      CHROME_INSTALLER:
        description: 'Please Provide the CHROME_INSTALLER'
        default: 'VSCodeUserSetup-x64-1.66.0.exe'
        required: true
      ARM_ENVIRONMENT_NAME:
        type: choice
        description: 'Please Provide the Environtment'
        options: 
        - Production
        - Development
        - Test
     
      

jobs:
  CreatingPropertiesFiles:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ github.event.inputs.ARM_SERVER_NAME }} ${{ github.event.inputs.JAVA_INSTALLER }} 
