name: SQl DB REFRESH

on:
  workflow_dispatch:
    inputs:      
      sourceServer:
        description: 'Provide Source Server'
        required: true
      targetServer:
        description: 'Provide Target Server'
        required: true
env:
  CLUSTER_NAME: ${{ github.event.inputs.sourceServer }}
  
  
jobs:
  publish:
    runs-on: ubuntu-latest
   
    steps:
      - name: Get Azure credential
        id: get-cred
        run: |
          echo  ${{ env.CLUSTER_NAME }}
        if: env.CLUSTER_NAME == 'PSR'
          
 
