name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        
        default: 'Mona the Octocat'
      home:
        description: 'location'
        
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.MULE_ANYPOINT_USER_NAME }}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{secrets.MULE_AES_SECRET_KEY_PASSWORD}}' 
