name: ID Example

on:
  workflow_dispatch:
    inputs:      
      sourceServer:
        description: 'Provide Source Server'
        required: true
      targetServer:
        description: 'Provide Target Server'
        required: true
      rsvName:
        description: 'Provide RSV Server'
        required: true
      subcriptionId:
        description: 'Provide Subscription Server'
        required: true
      
jobs:
  publish:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "sourceServer: ${{ github.event.inputs.sourceServer }}"
          
 
