name: ID Example

on:
  workflow_dispatch:
    inputs:      
      sourceServer:
        description: 'Provide Source Server'
        required: true
     
jobs:
  publish:
    runs-on: ubuntu-latest
   
    steps:
      - name: Get Azure credential
        id: get-cred
        run: |
          env_name=${{ github.event.inputs.sourceServer }}
          if [[ $env_name == dev_01 ]]; then
            echo "::set-output name=login_cred::${{ secrets.DEV_01 }}"
          elif [[ $env_name == dev_02 ]]; then
            echo "::set-output name=login_cred::${{ secrets.DEV_02 }}"
          elif [[ $env_name == test_01 ]]; then
            echo "::set-output name=login_cred::${{ secrets.TEST_01 }}"
          elif [[ $env_name == test_02 ]]; then
            echo "::set-output name=login_cred::${{ secrets.TEST_02 }}"
          elif [[ $env_name == prd_01 ]]; then
            echo "::set-output name=login_cred::${{ secrets.PRD_01 }}"
          else
            echo "::set-output name=login_cred::${{ secrets.other_creds }}"
          fi
      - uses: actions/checkout@v2
      
      - run: |
          echo "sourceServer: ${{ steps.get-cred.outputs.login_cred }}"
          
 
