on:
  workflow_dispatch:
    inputs:
      
      serverName:
        description: 'Please Provide the Server Name'
        type: string
        required: true 
      

jobs:
  serverName:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ github.event.inputs.serverName }} 
