name: SQl DB REFRESH

on:
  workflow_dispatch:
    inputs:      
      sourceServer:
        description: 'Provide Source Server'
        required: true
      targetServer:
        description: 'Provide Target Server'
        required: true
env:
  TEST_RESULT: 'success'
  AZURE_TAGS: '${{ github.event.inputs.SourceServer }}'
jobs:
  setup-job:
    runs-on: ubuntu-latest
    outputs:
      var1: ${{ steps.set-variable.outputs.test }}
      var2: ${{ steps.set-variable.outputs.test1 }}
      var3: ${{ steps.set-variable.outputs.test2 }}
    steps:
      - uses: actions/checkout@v2
      - name: Set test variable
        
        id: set-variable-AzResource
        run: |
         
    
          ${{ env.AZURE_TAGS }} | ConvertFrom-Json
          
        shell: "pwsh"
