name: SQl DB REFRESH

on:
  workflow_dispatch:
    inputs:      
      sourceServer:
        description: 'Provide Source Server'
        required: true
      targetServer:
        description: 'Provide Target Server'
        required: true
env:
  TEST_RESULT: 'success'
jobs:
  setup-job:
    runs-on: ubuntu-latest
    outputs:
      var1: ${{ steps.set-variable.outputs.test }}
      var2: ${{ steps.set-variable.outputs.test1 }}
      var3: ${{ steps.set-variable.outputs.test2 }}
    steps:
      - uses: actions/checkout@v2
      - name: Set test variable
        id: set-variable
        run: |
          if [ ${{ github.ref }} != 'refs/heads/main' ]; then
            echo "IS NOT main branch"
            echo "::set-output name=test::abc"
          else
            echo "IS main branch"
            echo "::set-output name=test::123"
          fi
          echo "::set-output name=test1::test1"
          echo "::set-output name=test2::test2"
        shell: bash
      - name: Read exported variable
        run: |
          echo "OUTPUT: ${{ steps.check.test-env.test }}"
          echo "OUTPUT: ${{ steps.check.test-env.test1 }}"
          echo "OUTPUT: ${{ steps.check.test-env.test2 }}"
          

  subsequent-job:
    runs-on: ubuntu-latest
    needs: [setup-job]
    steps:
      - uses: actions/checkout@v2
      - name: Read exported variable
        run: |
          echo "OUTPUT: ${{needs.setup-job.outputs.var1}}"
          echo "OUTPUT: ${{needs.setup-job.outputs.var2}}"
          echo "OUTPUT: ${{needs.setup-job.outputs.var3}}"
