name: SQl DB REFRESH

on:
  workflow_dispatch:
    inputs:      
      sourceServer:
        description: 'Provide Source Server'
        required: true
      
env:
  TEST_RESULT: 'success'
  AZURE_TAGS: '${{ github.event.inputs.SourceServer }}'
  SCRIPTPATH: '.github/workflows'
jobs:
  setup-job:
    runs-on: ubuntu-latest
    outputs:
      var1: ${{ steps.set-variable.outputs.test }}
      var2: ${{ steps.set-variable.outputs.test1 }}
      var3: ${{ steps.set-variable.outputs.test2 }}
    steps:
      - uses: actions/checkout@v2      
      - name: Deploy Hub
        uses: azure/powershell@v1
        with:
          inlineScript: |
           ./${{ env.SCRIPTPATH }}/build.ps1 -jsonObject "${{env.AZURE_TAGS}}"
          azPSVersion: "latest"
