name: main
on:
  workflow_dispatch:

jobs:
  
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    #environment: 'Test'
    steps:
     - name: Set up secret file
       env:
        DEBUG_PASSWORD: ${{ secrets.HELOO }}
        DEBUG_SECRET_KEY: ${{ secrets.HELLO }}
       run: |
        echo $DEBUG_PASSWORD 
        echo $DEBUG_SECRET_KEY 
