name: main
on:
  workflow_dispatch:

jobs:
  
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    #environment: 'Test'
    steps:
     - uses: actions/checkout@v2
     - name: 'Pre-Check Source' 
       uses: azure/powershell@v1        
       with:
          inlineScript: |                       
            write-host "5asdd"
          azPSVersion: "latest"
