name: add-mask-test
on: 
  workflow_dispatch:
    inputs:
      secret:
        description: 'secret value'
        required: true
env:
  TEST_RESULT: 'HELLO'
jobs:
  my-job:
    runs-on: ubuntu-latest
    outputs:
      ssssss: ${{ steps.set-variable.outputs.a }}
    steps:
      - name: add-mask test
        shell: pwsh
        id: set-variable
        run: |
            $s='sub-jda-cld-solutions-01'
            $values= "${{secrets.HELLO}}"
            $values.clientSecret_1
          
           
  my-job1:
    runs-on: ubuntu-latest
    needs: [my-job]
    steps:
      - name: add-mask testsdsd
        run: |
          
          echo "${{needs.my-job.outputs.ssssss}}"
