name: add-mask-test
on: 
  workflow_dispatch:
    inputs:
      Subscription:
        type: choice
        description: 'Provide Subcription Name'
        options:
        - sub-by-cld-solutions-eus2-02
        - sub-by-cld-solutions-euw-02
        - sub-by-cld-solutions-ase-02
        - sub-by-cld-solutions-aue-02
        - sub-by-cld-byc-prod-01
        - sub-jda-cld-solutions-01
        - sub-by-cld-indsol-prod-01
        - sub1
        - sub2
env:
  TEST_RESULT: 'HELLO'
  SUBSCRIPTION: "${{ github.event.inputs.Subscription }}"
jobs:
  my-job:
    runs-on: ubuntu-latest
    outputs:
      ssssss: ${{ steps.set-variable.outputs.a }}
      
    
    
    steps:
      - name: 'Install Mule' 
        uses: azure/powershell@v1   
        with:
          inlineScript: |  
            ehco "hello"
          azPSVersion: "latest" 
        if: ${{ env.SUBSCRIPTION == 'sub-by-cld-byc-prod-01' }}
