name: main
on:
  workflow_dispatch:

jobs:
  
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    #environment: 'Test'
    steps:
     - id: sets-a-secret
       run: |
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "::set-output name=secret-number::$the_secret"
     - run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"
