# This is a basic workflow to help you get started with Actions

name: TEST1

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        type: choice
        description: 'Please Provide Server Regions'
        options:
        - Central US
        - East US 2
        - Southeast Asia
        - Australia East
        - West Europe
        
      
      SourceServer:
        description: 'Provide Source Server Name'     
        required: true
      SourceServer1:
        description: 'Provide Source Server Name'     
        required: true
      SourceServer2:
        description: 'Provide Source Server Name'     
        required: true
      SourceServer3:
        description: 'Provide Source Server Name'     
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  GETCREDS:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        shell: pwsh
        run: |
          write-Host "test"
        
  GETCREDS1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        shell: pwsh
        run: |
          write-Host "test"
